#include <stdio.h>

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 
10 terms will be: 1,2,3,5,8,13,21,33,54,89

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int final = 4000000;
int sum = 0;
int main(void){
    int prev = 0;
    for (int i = 1; i < final; i+=0)
    {
        int curr = i;
        i = curr + prev;
        prev = curr;
        if (i < final && i % 2 == 0)
        {
            sum += i;
            printf("%d \n",i);
        }
    }
    printf("%d \n", sum);
}